### ISSUE TITLE
Is db.c racy?

### ISSUE THREAD

**Issue by yanosz** [FieldTracks/JellingStone#10]
Is: 
1. There's a single db_add function called on each subject discovered. If it runs an parallel, the same subject is created multiple times, eventually.

2. When detecting a subject, can looks take to long? Atm we compare up to 300 entries (uudi - memcmp, 2 integer) => a few thousend instructions

Should:
1. Here:
* Either: Running in parallel should not create equal entries
* Or: Duplicates are pruned before sending
* Or: We know, that's not running in parallel
2. Make sure, that we're fast enough

**Comment by h-e-n-r-i-k** [comment]
1. We know that callbacks do not run in parallel. Callback events are put in a queue when they occur. The bluetooth stack runs a task that processes all callbacks in the queue successively. See [here](https://github.com/espressif/esp-idf/blob/master/components/bt/bluedroid/btc/core/btc_task.c#L110). We therefore don't need to worry about parallel execution.

2. The queue size is set to 60 elements by default, so we shouldn't need to worry about processing speed either.

As @yanosz noted: There might be concurrent access to our database after scanning when we read it out but yet unprocessed callbacks still write data into the database. I'll look into this and fix it.

**Comment by yanosz** [comment]
Fixed in the next-branch.
The slot-marker for submission is incremented after all fiedls are written. Hence, the main-task won't submit any data that is being written by the call-back task.
