### ISSUE TITLE
OTA

### ISSUE THREAD

**Issue by yanosz** [FieldTracks/JellingStone#3]
Is: Updates are installed using a serial cable

Should: Install Updates using a https-server

note: A http-client was recently introduced into esp-32

**Comment by h-e-n-r-i-k** [comment]
The bluetooth stack seems to be quite heavy. Building a small loader without it that loads the actual program and config (?!) via WiFi could reduce flashing time on the one hand but would be more unreliable on the other hand.

**Comment by yanosz** [comment]
No priority
