### ISSUE TITLE
Compression

### ISSUE THREAD

**Issue by yanosz** [FieldTracks/JellingStone#4]
Is: JSON-data is transmitted as is using mqtt

Should: JSON-data is optionally compressed using miniz / deflate

**Comment by h-e-n-r-i-k** [comment]
### Options
Miniz tries to allocate at least 160KB of memory on the heap which is way more than we have available (about 60KB on the ESP32). This makes miniz unusable for us.

While looking for alternatives we learned about [CBOR](http://cbor.io/), a data format for storing JSON like data in binary. It has a low memory footprint and various usable C libraries. However its focus lies rather on small code size than small message sizes.

### Compression
To compare both I made a quick test using the [example.json](https://github.com/FieldTracks/mqtt2sql/blob/7c709a6dfe84970e17ec77f230046fb499b016bc/example.json) data with removed whitespaces and newlines.

Compression | Data size | Compression ratio
----------- | --------- | -----------------
None | 292 bytes | 100%
CBOR | 245 bytes | 119%
deflate | 185 bytes | 158%

### Next steps
I would suggest to rather not use CBOR. There is lots of redundancy in our JSON data (even when packed in binary) and especially when multiple nodes at a time are reported. Compression algorithms or data formats that don't store description information are probably way better for our use case.

Ideas:
- Look for another compression format that can be handled by our microcontroller
- Find a deflate library that allows for adjusting the sliding window (and maybe other buffers) down to 1KB (or so), which should be sufficient for compressing our data
  - Or hack miniz to do so
- We need to develop a compact protocol for LoRaWAN anyway. Use this for WiFi transmission too.
- Use CBOR for its ease of use (?) and JSON compatibility
- Check if packet size is an actual problem

**Comment by h-e-n-r-i-k** [comment]
I chose zlib for compression, which provides some memory settings that allow reducing memory usage down to ~25KB. Compression can be enabled in menuconfig.
See #12
